name: Deployment Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest

    steps:
    - name: install ssh keys
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: connect and pull
      run: |
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
          cd ${{ secrets.WORK_DIR }} &&
          git fetch origin &&
          git reset --hard origin/${{ secrets.MAIN_BRANCH }}
        "
    - name: kill previous process (if running)
      run: |
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
          lsof -iTCP:9420 -sTCP:LISTEN -t | xargs kill || true
        "

    - name: run server
      run: |
    ssh -T ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
      screen -dmS SwiggleServer bash -c 'python3 -m http.server ${{ secrets.HTTP_PORT }}'
    "

    - name: cleanup
      run: rm -rf ~/.ssh
